### ISSUE TITLE
Caching custom methods with Ttl

### ISSUE THREAD

**Issue by rjsworking** [Torann/laravel-repository#2]
Hi
Thanks for sharing this awesome package.

I don't like to have find\* or other methods in the controller so I mostly use custom methods.
As I have different queries over the same repository, I also need to have different cache Ttl's or no cache at all.
Looking at your code, I've noticed in AbstractCacheDecorator.php - getCache() method (line 228) that the 4th parameter is $time but when you call the cache remember method, you don't pass along the $time parameter.

When caching custom methods, I could specify a ttl (30 minutes):

```
    public function getRecent($limit = 15)
    {
        return $this->getCache('getRecent', func_get_args(), function () use ($limit) {
            return $this->repo->getRecent($limit);
        }, 30 );
    }
```

And then, in the getCache() method, call the remember method with the $time param:

```
...
    return $this->cache->remember(
        $this->getCacheKey($method, $args),
        $callback,
        $time
    );
```

I think it is a nice and very useful improvement.

Cheers

**Comment by Torann** [comment]
Each repository is set to cache for 60 minutes by default. This can be overwritten in each repository using the `$cacheMinutes` variable. I see some changes that could be made so that each custom method could have a different time, but my need for this just hasn't come about on my end yet. So I have not plans of adding it. 

You can use `self::EXPIRES_END_OF_DAY` in the repository to have the repository determine the time until the end of the day.
